services:
  postgres:
    image: postgres:latest
    container_name: product-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: product-api
    ports:
      - "3000:3000"
    environment:
      - DB_USER=admin
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - NODE_ENV=production
    depends_on:
      postgres:
        condition: service_healthy